name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Укажите ветку, для которой хотите настроить деплой

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'  # Укажите версию Node.js, если ваш проект требует её

      - name: Install dependencies
        run: npm install  # Если у вас есть зависимостя

      - name: Build
        run: npm run build  # Замените на команду сборки вашего проекта

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Укажите папку с собранными файлами, которую нужно опубликовать
